FROM ubuntu:18.04

RUN apt update -y && \
    apt upgrade -y

RUN apt-get install -y git \
                 unzip \
                 zip \
				 wget \
				 automake \
                 autoconf \
                 pkg-config \
                 libcurl4-openssl-dev \
                 libjansson-dev \
                 libssl-dev \
                 libgmp-dev \
                 zlib1g-dev 

RUN git clone -v https://github.com/fireworm71/veriumMiner ~/git/veriumminer/

RUN ~/git/veriumminer/build.sh

RUN ~/git/veriumminer/autogen.sh

RUN ~/git/veriumminer/configure CFLAGS= --with-crypto --with-curl

RUN ~/git/veriumminer/make -j4

RUN cp ~/git/veriumminer/src/cpuminer /usr/bin/
